# Minimal Funky Trees environment for Python debugging
# generated by AI! :D

from math import *

# special variable
delta = 0.0 # time difference between current and last frame in seconds

# flight inputs
Pitch = 0.0
Roll = 0.0
Yaw = 0.0
Throttle = 0.0
Brake = 0.0
Trim = 0.0
VTOL = 0.0
LandingGear = 0
FireGuns = False
FireWeapons = False
LaunchCountermeasures = False
Activate1 = False
Activate2 = False
Activate3 = False
Activate4 = False
Activate5 = False
Activate6 = False
Activate7 = False
Activate8 = False

# flight data
Altitude = 0.0 # - Aircraft's altitude in metres
AltitudeAgl = 0.0 # - Aircraft's altitude above ground level in metres
GS = 0.0 # - The speed relative to the ground (m/s)
IAS = 0.0 # - The speed relative to the air, adjusted for the desnity of the air (m/s)
TAS = 0.0 # - The speed relative to the air (m/s)
Fuel = 1.0 # - The amount of fuel remaining as a proportion of capacity (0 to 1)
AngleOfAttack = 0.0 # - The angle of attack (angle airflow vertically meets the boresight) in degrees
AngleOfSlip = 0.0 # - The horizontal equivalent of angle of attack (degrees)
PitchAngle = 0.0 # - The pitch of the aircraft (degrees)
RollAngle = 0.0 # - The roll of the aircraft (degrees)
Heading = 0.0 # - The heading of the aircraft (degrees)
Time = 0.0 # - The time since the level loaded (seconds)
GForce = 0.0 # - The acceleration and gravitational "force" acting on the cockpit in G. I know it's not a force. Shut up.
GearDown = False # - true if the landing gear is down, else false.
VerticalG = 0.0 # - The signed vertical component of the "G Force".
SelectedWeaponName = "MyWeapon" # - The name of the selected weapon
Latitude = 0.0 # - The North/South position of the craft (metres)
Longitude = 0.0 # - The East/West position of the craft (metres)
PitchRate = 0.0 # - The pitch angular velocity in degrees/second
YawRate = 0.0 # - The yaw angular velocity in degrees/second
RollRate = 0.0 # - The roll angular velocity in degrees/second (these 3 inputs are better than using rate(PitchAngle) etc, because they account for wrapping around the angle, as well as being in local space: rate(Heading) is different to YawRate)
TargetSelected = False # - true if a target is selected, else false.
TargetHeading = 0.0 # - the heading to the selected target in degrees.
TargetElevation = 0.0 # - the vertical angle to the selected target in degrees.
TargetDistance = 0.0 # - the distance to the selected target in metres.

# Funky Trees functions
def ammo(name):
    return 8

def clamp(x, min_val, max_val):
    return max(min_val, min(x, max_val))

def clamp01(x):
    return clamp(x, 0.0, 1.0)

def ceil(x):
    return int(x) if x == int(x) else int(x) + 1

def deltaangle(a, b):
    delta = (b - a) % 360
    return delta if delta <= 180 else delta - 360

def exp(x):
    return e ** x

def floor(x):
    return int(x) if x >= 0 else int(x) - 1

def inverselerp(a, b, x):
    return (x - a) / (b - a) if b != a else 0

def lerpangle(a, b, t):
    delta = deltaangle(a, b)
    return a + delta * t

def lerp(a, b, t):
    return clamp(a + (b - a) * t, min(a, b), max(a, b))

def lerpunclamped(a, b, t):
    return a + (b - a) * t

def log10(x):
    return log(x, 10)

def pingpong(x, length):
    l = length * 2
    x = x % l
    return x if x < length else l - x

def pow(x, p):
    return x**p

def repeat(x, l):
    return x % l if l != 0 else 0

def round(x):
    return int(x + 0.5) if x >= 0 else int(x - 0.5)

def sign(x):
    return 1 if x > 0 else -1 if x < 0 else 0

def smoothstep(a, b, t):
    t = clamp01((t - a) / (b - a))
    return t * t * (3 - 2 * t)

def sum(x):
    if not hasattr(sum, 'total'):
        sum.total = 0
    sum.total += x
    return sum.total

def rate(x):
    if not hasattr(rate, 'last_value'):
        rate.last_value = x
        return 0
    delta = x - rate.last_value
    rate.last_value = x
    return delta

def smooth(x, t):
    if not hasattr(smooth, 'output'):
        smooth.output = x
    max_change = t
    if smooth.output < x:
        smooth.output = min(smooth.output + max_change, x)
    else:
        smooth.output = max(smooth.output - max_change, x)
    return smooth.output

def PID(target, current, p, i, d):
    error = target - current
    return p * error + i * sum(error) - d * rate(current)